version: "3.9"
volumes:
  db_data:
  
services:    
    edusmsapp:
        container_name: edusmsapp
        depends_on:
            - localdb
        build:
            context: .
            dockerfile: docker/Dockerfile
        image: edusms
        restart: unless-stopped
        volumes:
            - ./:/var/www/html
    
    nginx:
        image: nginx:alpine
        container_name: eduserver
        depends_on:
            - edusmsapp
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www/html
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    
    localdb:
        container_name: edusmsdb
        image: mariadb:latest
        restart: unless-stopped
        ports:
            - 3306
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - db_data:/var/lib/mysql
            - ./docker/log:/var/log/mysql
            - ./docker/db/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
            - ./docker/db/conf.d:/etc/mysql/conf.d

