version: "3.9"
# mysql -u root --password="0passlla07" --execute="show master status;"
volumes:
  db_data:
  
services:
    # website:
    #     container_name: website
    #     build:
    #         context:  .
    #         dockerfile: Dockerfile
    #     restart: unless-stopped
    #     image: lla-website:latest
    #     ports:
    #     - 3000
    #     volumes:
    #     - /home/beznet/website:/var/www/html/website:rw
      
    app:
        restart: unless-stopped
        build:
            context: .
            dockerfile: docker/Dockerfile
        image: edusms
        ports:
            - 3000
        container_name: webapp
        volumes:
        - ./:/var/www

    mariadb:
        image: mariadb:latest
        container_name: lladb
        restart: unless-stopped
        ports:
        - 3306
        environment:
            MYSQL_ROOT_PASSWORD: 0passlla07
            MYSQL_DATABASE: lladb
            MYSQL_USER: lla
            MYSQL_PASSWORD: 14w0rdlla
        volumes:
        - db_data:/var/lib/mysql
        - ./docker/log:/var/log/mysql
        - ./docker/db/init:/docker-entrypoint-initdb.d
        - ./docker/db/conf.d:/etc/mysql/conf.d

    # adminer:
    #     depends_on:
    #     - mariadb
    #     image: adminer
    #     container_name: dbclient
    #     restart: always
    #     environment:
    #         ADMINER_DESIGN: hydra
    #         ADMINER_DEFAULT_SERVER: mariadb
    #     ports:
    #         - 8080
    
    nginx:
        image: nginx:alpine
        container_name: travellist-nginx
        restart: unless-stopped
        ports:
        - 8000:80
        volumes:
        - ./:/var/www
        - ./docker/nginx:/etc/nginx/conf.d/